from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

from builder_profile.models import ProfileData


def generate_html_report(profile: ProfileData, output_dir: Path) -> Path:
    html_path = output_dir / "profile.html"
    html_path.write_text(_render_html(profile))
    print(f"  HTML: {html_path}", file=sys.stderr)
    return html_path


def _render_html(profile: ProfileData) -> str:
    date_from = profile.date_range.get("from", "")[:10]
    date_to = profile.date_range.get("to", "")[:10]
    total_sessions = sum(r.get("sessions", 0) for r in profile.repos)
    total_commits = sum(r.get("commits", 0) for r in profile.repos)

    scores_html = _render_scores(profile.aggregate_scores)
    repos_html = _render_repos(profile.repos)
    streams_html = _render_streams(profile.work_streams)
    auto_html = _render_automation(profile.automated_streams)
    velocity_html = _render_velocity_chart(profile.velocity_timeline)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Builder Profile</title>
<style>
:root {{
  --bg: #0d1117; --surface: #161b22; --border: #30363d;
  --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
  --green: #3fb950; --red: #f85149; --yellow: #d29922;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 1100px; margin: 0 auto; }}
h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
h2 {{ font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
h3 {{ font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }}
.meta {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }}
.card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1.2rem; margin-bottom: 1rem; }}
.narrative {{ line-height: 1.8; margin-bottom: 1rem; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 1rem; }}
th, td {{ padding: 0.6rem 0.8rem; text-align: left; border-bottom: 1px solid var(--border); }}
th {{ color: var(--muted); font-weight: 600; font-size: 0.85rem; text-transform: uppercase; }}
.score {{ display: inline-block; width: 2rem; text-align: center; font-weight: 700; border-radius: 4px; padding: 2px 0; }}
.score-1, .score-2 {{ background: #f8514922; color: var(--red); }}
.score-3 {{ background: #d2992222; color: var(--yellow); }}
.score-4 {{ background: #3fb95022; color: var(--green); }}
.score-5 {{ background: #3fb95044; color: var(--green); }}
.bar-container {{ display: flex; align-items: center; gap: 0.5rem; }}
.bar {{ height: 8px; border-radius: 4px; background: var(--accent); min-width: 2px; }}
.loc-add {{ color: var(--green); }}
.loc-del {{ color: var(--red); }}
.stream-meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 0.5rem; }}
.chart-row {{ display: flex; align-items: center; gap: 0.5rem; margin: 3px 0; font-size: 0.8rem; }}
.chart-label {{ width: 70px; text-align: right; color: var(--muted); flex-shrink: 0; }}
.chart-bar {{ height: 14px; border-radius: 3px; min-width: 1px; }}
.chart-val {{ color: var(--muted); width: 40px; flex-shrink: 0; }}
.decisions {{ list-style: none; }}
.decisions li {{ padding: 0.3rem 0; font-size: 0.9rem; }}
.decisions li::before {{ content: "\\2022"; color: var(--accent); margin-right: 0.5rem; }}
footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
  color: var(--muted); font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<h1>Builder Profile</h1>
<div class="meta">
  {date_from} to {date_to} &middot;
  {len(profile.repos)} repos &middot;
  {total_sessions} sessions &middot;
  {total_commits} commits
</div>

{"<div class='card narrative'>" + profile.profile_narrative + "</div>" if profile.profile_narrative else ""}

{scores_html}
{repos_html}
{velocity_html}
{streams_html}
{auto_html}

<footer>Generated by builder-profile v{profile.tool_version} on {datetime.now().strftime("%Y-%m-%d")}</footer>
</body>
</html>"""


def _render_scores(scores: dict) -> str:
    if not scores:
        return ""

    rows = []
    for axis, data in scores.items():
        if not isinstance(data, dict):
            continue
        score = data.get("score", 0)
        label = axis.replace("_", " ").title()
        score_class = f"score-{min(int(score), 5)}"
        bar_width = int(score * 20)
        justification = data.get("justification", "")
        rows.append(
            f"<tr><td>{label}</td>"
            f"<td><span class='score {score_class}'>{score}</span></td>"
            f"<td><div class='bar-container'><div class='bar' style='width:{bar_width}%'></div></div></td>"
            f"<td style='color:var(--muted);font-size:0.85rem'>{justification}</td></tr>"
        )

    if not rows:
        return ""

    return f"""<h2>Scoring Summary</h2>
<div class="card">
<table>
<tr><th>Axis</th><th>Score</th><th style="width:20%">Visual</th><th>Justification</th></tr>
{"".join(rows)}
</table>
</div>"""


def _render_repos(repos: list[dict]) -> str:
    if not repos:
        return ""

    rows = []
    for r in repos:
        name = r.get("name", "unknown")
        sess = r.get("sessions", 0)
        commits = r.get("commits", 0)
        loc_a = r.get("loc_added", 0)
        loc_d = r.get("loc_deleted", 0)
        stack = ", ".join(r.get("tech_stack", [])[:4])
        rows.append(
            f"<tr><td><strong>{name}</strong></td><td>{sess}</td><td>{commits}</td>"
            f"<td><span class='loc-add'>+{loc_a}</span> / <span class='loc-del'>-{loc_d}</span></td>"
            f"<td style='color:var(--muted)'>{stack}</td></tr>"
        )

    return f"""<h2>Projects</h2>
<div class="card">
<table>
<tr><th>Project</th><th>Sessions</th><th>Commits</th><th>LOC</th><th>Stack</th></tr>
{"".join(rows)}
</table>
</div>"""


def _render_stream_scores(ws) -> str:
    if not ws.scores:
        return ""
    parts = []
    for axis, data in ws.scores.items():
        if not isinstance(data, dict):
            continue
        s = data.get("score", 0)
        sc = f"score-{min(int(s), 5)}"
        label = axis.replace("_", " ").title()
        parts.append(f"<span class='score {sc}'>{s}</span> {label}")
    if not parts:
        return ""
    return "<div style='margin-top:0.5rem'>" + " &middot; ".join(parts) + "</div>"


def _render_stream_card(ws) -> str:
    start = ws.start_time.strftime("%Y-%m-%d") if ws.start_time else "?"
    end = ws.end_time.strftime("%Y-%m-%d") if ws.end_time else "?"
    narrative_block = f"<div class='narrative'>{ws.narrative}</div>" if ws.narrative else ""
    decisions_block = ""
    if ws.decisions:
        items = "".join(f"<li>{d}</li>" for d in ws.decisions[:5])
        decisions_block = f"<ul class='decisions'>{items}</ul>"

    return f"""<div class="card">
<h3>{ws.title}</h3>
<div class="stream-meta">{ws.project} &middot; {start} to {end} &middot;
{len(ws.sessions)} sessions &middot; {len(ws.commits)} commits &middot;
<span class="loc-add">+{ws.loc_added}</span>/<span class="loc-del">-{ws.loc_deleted}</span> LOC</div>
{narrative_block}{_render_stream_scores(ws)}{decisions_block}
</div>"""


def _render_streams(streams: list) -> str:
    if not streams:
        return ""
    cards = [_render_stream_card(ws) for ws in streams]
    return "<h2>Work Streams</h2>\n" + "\n".join(cards)


def _render_automation(streams: list) -> str:
    if not streams:
        return ""

    total_sessions = sum(len(ws.sessions) for ws in streams)
    total_commits = sum(len(ws.commits) for ws in streams)
    total_loc = sum(ws.loc_added + ws.loc_deleted for ws in streams)

    items = []
    for ws in streams[:15]:
        start = ws.start_time.strftime("%Y-%m-%d") if ws.start_time else "?"
        items.append(
            f"<li><strong>{ws.title}</strong> ({start}) - "
            f"{len(ws.sessions)} sessions, "
            f"<span class='loc-add'>+{ws.loc_added}</span>/<span class='loc-del'>-{ws.loc_deleted}</span> LOC</li>"
        )

    return f"""<h2>Automation &amp; CI</h2>
<div class="card">
<p><strong>{total_sessions}</strong> automated sessions across
<strong>{len(streams)}</strong> work streams,
producing <strong>{total_commits}</strong> commits
and <strong>{total_loc:,}</strong> LOC changed.</p>
<ul class="decisions">{"".join(items)}</ul>
</div>"""


def _render_velocity_chart(timeline: list[dict]) -> str:
    if not timeline:
        return ""

    recent = timeline[-16:]
    max_sessions = max((w.get("sessions", 0) for w in recent), default=1) or 1
    max_commits = max((w.get("commits", 0) for w in recent), default=1) or 1

    rows = []
    for w in recent:
        week = w.get("week", "")
        sess = w.get("sessions", 0)
        commits = w.get("commits", 0)
        sess_pct = int(sess / max_sessions * 100)
        commit_pct = int(commits / max_commits * 100)
        rows.append(f"""<div class="chart-row">
<span class="chart-label">{week}</span>
<div class="chart-bar" style="width:{sess_pct}%;background:var(--accent)" title="{sess} sessions"></div>
<span class="chart-val">{sess}s</span>
<div class="chart-bar" style="width:{commit_pct}%;background:var(--green)" title="{commits} commits"></div>
<span class="chart-val">{commits}c</span>
</div>""")

    return f"""<h2>Velocity</h2>
<div class="card">
<div style="font-size:0.8rem;color:var(--muted);margin-bottom:0.5rem">
<span style="color:var(--accent)">&#9632;</span> Sessions
<span style="color:var(--green);margin-left:1rem">&#9632;</span> Commits
</div>
{"".join(rows)}
</div>"""
